import { z } from 'zod'

export const fornecedorSchema = z.object({
  cnpj: z.string().optional(),
  razaoSocial: z.string().min(2, 'Razão social é obrigatória.'),
  nomeFantasia: z.string().min(2, 'Nome fantasia é obrigatório.'),
  tipoPessoa: z.string().optional(),
  inscricaoEstadual: z.string().optional(),
  inscricaoMunicipal: z.string().optional(),
  categoriaFornecedor: z.string().optional(),
  tipoFornecimento: z.string().optional(),
  nomeContatoPrincipal: z.string().optional(),
  telefone: z.string().optional(),
  whatsapp: z.string().optional(),
  email: z.string().email('E-mail inválido.').or(z.literal('')).optional(),
  emailFinanceiro: z.string().email('E-mail inválido.').or(z.literal('')).optional(),
  site: z.string().optional(),
  cep: z.string().optional(),
  logradouro: z.string().optional(),
  numero: z.string().optional(),
  complemento: z.string().optional(),
  bairro: z.string().optional(),
  cidade: z.string().optional(),
  estado: z.string().length(2, 'Use a sigla do estado (Ex: SP).').or(z.literal('')).optional(),
  pais: z.string().optional(),
  prazoEntregaMedioDias: z.string().regex(/^\d+$/, 'Deve ser um número inteiro.').or(z.literal('')).optional(),
  condicaoPagamento: z.string().optional(),
  limiteCredito: z.string().regex(/^\d+(\.\d{1,2})?$/, 'Formato inválido. Use ponto.').or(z.literal('')).optional(),
  fornecePecas: z.boolean().optional(),
  forneceServicos: z.boolean().optional(),
  forneceFerramentas: z.boolean().optional(),
  forneceInsumos: z.boolean().optional(),
  forneceTecnologia: z.boolean().optional(),
  aceitaPedidoUrgente: z.boolean().optional(),
  avaliacao: z.string().regex(/^[1-5]$/, 'Nota de 1 a 5.').or(z.literal('')).optional(),
  observacoesComerciais: z.string().optional(),
  observacoesInternas: z.string().optional(),
  status: z.string().optional(),
  ativo: z.boolean().optional(),
})
