export const CATALOGO_DADOS = {
  servicos: [
    { id: 'S1', descricao: 'Troca de óleo', detalhes: 'Substituição do óleo do motor', preco: 120.00 },
    { id: 'S2', descricao: 'Troca de filtro de óleo', detalhes: 'Substituição do filtro', preco: 60.00 },
    { id: 'S3', descricao: 'Troca de filtro de ar', detalhes: 'Substituição do filtro de ar do motor', preco: 50.00 },
    { id: 'S4', descricao: 'Troca de filtro de combustível', detalhes: 'Substituição do filtro', preco: 80.00 },
    { id: 'S5', descricao: 'Troca de filtro de cabine', detalhes: 'Substituição do filtro interno', preco: 60.00 },
    { id: 'S6', descricao: 'Revisão básica', detalhes: 'Check-up geral', preco: 180.00 },
    { id: 'S7', descricao: 'Revisão intermediária', detalhes: 'Check-up completo', preco: 350.00 },
    { id: 'S8', descricao: 'Revisão completa', detalhes: 'Revisão geral com ajustes', preco: 600.00 },
    { id: 'S9', descricao: 'Verificação de níveis', detalhes: 'Óleo, água, fluídos', preco: 50.00 },
    { id: 'S10', descricao: 'Lubrificação geral', detalhes: 'Pontos móveis', preco: 90.00 },
    { id: 'S11', descricao: 'Alinhamento', detalhes: 'Ajuste da direção', preco: 120.00 },
    { id: 'S12', descricao: 'Balanceamento', detalhes: 'Balanceamento de rodas', preco: 100.00 },
    { id: 'S13', descricao: 'Alinhamento + balanceamento', detalhes: 'Combo completo', preco: 200.00 },
    { id: 'S14', descricao: 'Troca de amortecedor', detalhes: 'Substituição (par)', preco: 300.00 },
    { id: 'S15', descricao: 'Troca de mola', detalhes: 'Substituição (par)', preco: 280.00 },
    { id: 'S16', descricao: 'Troca de pivô', detalhes: 'Substituição da peça', preco: 150.00 },
    { id: 'S17', descricao: 'Troca de bandeja', detalhes: 'Substituição da bandeja', preco: 220.00 },
    { id: 'S18', descricao: 'Troca de terminal de direção', detalhes: 'Interno ou externo', preco: 140.00 },
    { id: 'S19', descricao: 'Verificação de suspensão', detalhes: 'Inspeção completa', preco: 100.00 },
    { id: 'S20', descricao: 'Ajuste de caixa de direção', detalhes: 'Correção de folgas', preco: 180.00 },
    { id: 'S21', descricao: 'Troca de pastilhas', detalhes: 'Substituição pastilhas', preco: 180.00 },
    { id: 'S22', descricao: 'Troca de discos', detalhes: 'Substituição dos discos', preco: 250.00 },
    { id: 'S23', descricao: 'Retífica de discos', detalhes: 'Correção de discos', preco: 160.00 },
    { id: 'S24', descricao: 'Troca de fluido de freio', detalhes: 'Sangria e substituição', preco: 120.00 },
    { id: 'S25', descricao: 'Revisão do sistema de freios', detalhes: 'Inspeção completa', preco: 150.00 },
    { id: 'S26', descricao: 'Troca de cilindro mestre', detalhes: 'Substituição', preco: 280.00 },
    { id: 'S27', descricao: 'Troca de servo-freio', detalhes: 'Substituição', preco: 350.00 },
    { id: 'S28', descricao: 'Ajuste de freio traseiro', detalhes: 'Regulagem', preco: 90.00 },
    { id: 'S29', descricao: 'Verificação ABS', detalhes: 'Diagnóstico', preco: 120.00 },
    { id: 'S30', descricao: 'Troca de lonas', detalhes: 'Substituição', preco: 200.00 },
    { id: 'S31', descricao: 'Diagnóstico eletrônico', detalhes: 'Scanner veicular', preco: 150.00 },
    { id: 'S32', descricao: 'Troca de bateria', detalhes: 'Substituição', preco: 80.00 },
    { id: 'S33', descricao: 'Teste de bateria', detalhes: 'Avaliação', preco: 50.00 },
    { id: 'S34', descricao: 'Troca de alternador', detalhes: 'Substituição', preco: 300.00 },
    { id: 'S35', descricao: 'Troca de motor de partida', detalhes: 'Substituição', preco: 280.00 },
    { id: 'S36', descricao: 'Reparação elétrica simples', detalhes: 'Fusíveis, fios', preco: 120.00 },
    { id: 'S37', descricao: 'Reparação elétrica complexa', detalhes: 'Chicotes', preco: 350.00 },
    { id: 'S38', descricao: 'Troca de lâmpadas', detalhes: 'Faróis ou lanternas', preco: 60.00 },
    { id: 'S39', descricao: 'Ajuste de faróis', detalhes: 'Regulagem', preco: 80.00 },
    { id: 'S40', descricao: 'Reset de módulos', detalhes: 'Reprogramação', preco: 100.00 },
    { id: 'S41', descricao: 'Troca de líquido de arrefecimento', detalhes: 'Substituição', preco: 150.00 },
    { id: 'S42', descricao: 'Limpeza do sistema', detalhes: 'Flush', preco: 200.00 },
    { id: 'S43', descricao: 'Troca de radiador', detalhes: 'Substituição', preco: 350.00 },
    { id: 'S44', descricao: 'Troca de válvula termostática', detalhes: 'Substituição', preco: 180.00 },
    { id: 'S45', descricao: 'Troca de mangueiras', detalhes: 'Substituição', preco: 120.00 },
    { id: 'S46', descricao: 'Carga de ar-condicionado', detalhes: 'Gás refrigerante', preco: 180.00 },
    { id: 'S47', descricao: 'Higienização do ar', detalhes: 'Limpeza interna', preco: 120.00 },
    { id: 'S48', descricao: 'Troca de compressor AC', detalhes: 'Substituição', preco: 600.00 },
    { id: 'S49', descricao: 'Troca de condensador', detalhes: 'Substituição', preco: 400.00 },
    { id: 'S50', descricao: 'Diagnóstico do ar-condicionado', detalhes: 'Avaliação', preco: 150.00 },
    { id: 'S51', descricao: 'Troca de correia dentada', detalhes: 'Substituição', preco: 450.00 },
    { id: 'S52', descricao: 'Troca de correia auxiliar', detalhes: 'Substituição', preco: 200.00 },
    { id: 'S53', descricao: 'Ajuste de válvulas', detalhes: 'Regulagem', preco: 380.00 },
    { id: 'S54', descricao: 'Troca de embreagem', detalhes: 'Substituição', preco: 700.00 },
    { id: 'S55', descricao: 'Retífica parcial', detalhes: 'Serviço parcial', preco: 1200.00 },
    { id: 'S56', descricao: 'Retífica completa', detalhes: 'Motor completo', preco: 3500.00 },
    { id: 'S57', descricao: 'Troca de coxins', detalhes: 'Substituição', preco: 250.00 },
    { id: 'S58', descricao: 'Limpeza de bicos', detalhes: 'Ultrassom', preco: 220.00 },
    { id: 'S59', descricao: 'Troca de bomba de combustível', detalhes: 'Substituição', preco: 300.00 },
    { id: 'S60', descricao: 'Troca de bomba d’água', detalhes: 'Substituição', preco: 280.00 },
    { id: 'S61', descricao: 'Check-up pré-viagem', detalhes: 'Inspeção completa', preco: 150.00 },
    { id: 'S62', descricao: 'Inspeção veicular', detalhes: 'Avaliação técnica', preco: 120.00 },
    { id: 'S63', descricao: 'Ajuste de portas', detalhes: 'Regulagem', preco: 100.00 },
    { id: 'S64', descricao: 'Ajuste de capô', detalhes: 'Regulagem', preco: 90.00 },
    { id: 'S65', descricao: 'Troca de palhetas', detalhes: 'Substituição', preco: 60.00 },
    { id: 'S66', descricao: 'Troca de escapamento', detalhes: 'Substituição', preco: 300.00 },
    { id: 'S67', descricao: 'Solda de escapamento', detalhes: 'Reparo', preco: 150.00 },
    { id: 'S68', descricao: 'Limpeza do motor', detalhes: 'Higienização', preco: 180.00 },
    { id: 'S69', descricao: 'Polimento técnico', detalhes: 'Polimento', preco: 250.00 },
    { id: 'S70', descricao: 'Cristalização', detalhes: 'Proteção pintura', preco: 350.00 },
    { id: 'S71', descricao: 'Inspeção periódica frota', detalhes: 'Check-up múltiplo', preco: 120.00 },
    { id: 'S72', descricao: 'Manutenção preventiva frota', detalhes: 'Serviço padrão', preco: 300.00 },
    { id: 'S73', descricao: 'Laudo técnico', detalhes: 'Relatório técnico', preco: 200.00 },
    { id: 'S74', descricao: 'Diagnóstico pré-compra', detalhes: 'Avaliação completa', preco: 250.00 },
    { id: 'S75', descricao: 'Controle de emissões', detalhes: 'Análise', preco: 180.00 },
    { id: 'S76', descricao: 'Ajuste de injeção eletrônica', detalhes: 'Regulagem', preco: 300.00 },
    { id: 'S77', descricao: 'Atualização de software ECU', detalhes: 'Reprogramação', preco: 350.00 },
    { id: 'S78', descricao: 'Instalação de acessórios', detalhes: 'Mão de obra', preco: 150.00 },
    { id: 'S79', descricao: 'Instalação de alarme', detalhes: 'Instalação', preco: 200.00 },
    { id: 'S80', descricao: 'Instalação de som', detalhes: 'Instalação', preco: 250.00 },
    { id: 'S81', descricao: 'Diagnóstico de falha intermitente', detalhes: 'Análise profunda', preco: 300.00 },
    { id: 'S82', descricao: 'Diagnóstico de consumo excessivo', detalhes: 'Avaliação', preco: 200.00 },
    { id: 'S83', descricao: 'Diagnóstico de ruídos', detalhes: 'Identificação', preco: 180.00 },
    { id: 'S84', descricao: 'Diagnóstico de vibração', detalhes: 'Avaliação', preco: 220.00 },
    { id: 'S85', descricao: 'Teste de compressão', detalhes: 'Avaliação motor', preco: 150.00 },
    { id: 'S86', descricao: 'Teste de vazamento', detalhes: 'Leakdown', preco: 180.00 },
    { id: 'S87', descricao: 'Análise de gases', detalhes: 'Emissões', preco: 120.00 },
    { id: 'S88', descricao: 'Diagnóstico de transmissão', detalhes: 'Avaliação', preco: 350.00 },
    { id: 'S89', descricao: 'Diagnóstico elétrico avançado', detalhes: 'Análise profunda', preco: 400.00 },
    { id: 'S90', descricao: 'Diagnóstico completo premium', detalhes: 'Full check', preco: 600.00 },
    { id: 'S91', descricao: 'Revisão pós-serviço', detalhes: 'Inspeção', preco: 100.00 },
    { id: 'S92', descricao: 'Reaperto geral', detalhes: 'Ajustes finais', preco: 90.00 },
    { id: 'S93', descricao: 'Limpeza interna', detalhes: 'Higienização', preco: 150.00 },
    { id: 'S94', descricao: 'Limpeza externa', detalhes: 'Lavagem técnica', preco: 120.00 },
    { id: 'S95', descricao: 'Revisão de garantia', detalhes: 'Avaliação', preco: 130.00 },
    { id: 'S96', descricao: 'Ajuste eletrônico fino', detalhes: 'Parametrização', preco: 180.00 },
    { id: 'S97', descricao: 'Troca de sensores', detalhes: 'Substituição', preco: 200.00 },
    { id: 'S98', descricao: 'Teste rodagem', detalhes: 'Avaliação dinâmica', preco: 100.00 },
    { id: 'S99', descricao: 'Checklist entrega', detalhes: 'Conferência final', preco: 80.00 },
    { id: 'S100', descricao: 'Atendimento emergencial', detalhes: 'Serviço prioritário', preco: 300.00 }
  ],
  pecas: [
    { id: 'P1', descricao: 'Óleo do motor 5W30', detalhes: 'Lubrificante sintético', preco: 65.00 },
    { id: 'P2', descricao: 'Óleo do motor 10W40', detalhes: 'Lubrificante semissintético', preco: 55.00 },
    { id: 'P3', descricao: 'Filtro de óleo', detalhes: 'Filtragem do óleo', preco: 35.00 },
    { id: 'P4', descricao: 'Filtro de ar', detalhes: 'Filtragem do ar', preco: 45.00 },
    { id: 'P5', descricao: 'Filtro de combustível', detalhes: 'Filtragem do combustível', preco: 60.00 },
    { id: 'P6', descricao: 'Filtro de cabine', detalhes: 'Filtragem do ar interno', preco: 50.00 },
    { id: 'P7', descricao: 'Fluido de freio DOT 4', detalhes: 'Fluido hidráulico', preco: 40.00 },
    { id: 'P8', descricao: 'Aditivo radiador', detalhes: 'Proteção térmica', preco: 35.00 },
    { id: 'P9', descricao: 'Pastilha de freio dianteira', detalhes: 'Conjunto', preco: 180.00 },
    { id: 'P10', descricao: 'Pastilha de freio traseira', detalhes: 'Conjunto', preco: 160.00 },
    { id: 'P11', descricao: 'Disco de freio dianteiro', detalhes: 'Unidade', preco: 220.00 },
    { id: 'P12', descricao: 'Disco de freio traseiro', detalhes: 'Unidade', preco: 200.00 },
    { id: 'P13', descricao: 'Lona de freio', detalhes: 'Conjunto', preco: 140.00 },
    { id: 'P14', descricao: 'Cilindro mestre', detalhes: 'Sistema hidráulico', preco: 320.00 },
    { id: 'P15', descricao: 'Servo-freio', detalhes: 'Assistência de frenagem', preco: 450.00 },
    { id: 'P16', descricao: 'Amortecedor dianteiro', detalhes: 'Unidade', preco: 350.00 },
    { id: 'P17', descricao: 'Amortecedor traseiro', detalhes: 'Unidade', preco: 320.00 },
    { id: 'P18', descricao: 'Mola helicoidal', detalhes: 'Unidade', preco: 280.00 },
    { id: 'P19', descricao: 'Bandeja de suspensão', detalhes: 'Unidade', preco: 300.00 },
    { id: 'P20', descricao: 'Pivô de suspensão', detalhes: 'Unidade', preco: 140.00 },
    { id: 'P21', descricao: 'Terminal de direção', detalhes: 'Unidade', preco: 150.00 },
    { id: 'P22', descricao: 'Barra estabilizadora', detalhes: 'Unidade', preco: 260.00 },
    { id: 'P23', descricao: 'Coxim do amortecedor', detalhes: 'Unidade', preco: 120.00 },
    { id: 'P24', descricao: 'Bateria 60Ah', detalhes: 'Bateria automotiva', preco: 520.00 },
    { id: 'P25', descricao: 'Alternador', detalhes: 'Geração de energia', preco: 850.00 },
    { id: 'P26', descricao: 'Motor de partida', detalhes: 'Arranque', preco: 780.00 },
    { id: 'P27', descricao: 'Velas de ignição', detalhes: 'Jogo', preco: 160.00 },
    { id: 'P28', descricao: 'Cabo de vela', detalhes: 'Jogo', preco: 140.00 },
    { id: 'P29', descricao: 'Sensor de oxigênio', detalhes: 'Sonda lambda', preco: 320.00 },
    { id: 'P30', descricao: 'Sensor MAP', detalhes: 'Pressão do coletor', preco: 280.00 },
    { id: 'P31', descricao: 'Sensor de rotação', detalhes: 'Sensor do motor', preco: 220.00 },
    { id: 'P32', descricao: 'Lâmpada farol', detalhes: 'Unidade', preco: 45.00 },
    { id: 'P33', descricao: 'Radiador', detalhes: 'Arrefecimento', preco: 650.00 },
    { id: 'P34', descricao: 'Ventoinha', detalhes: 'Resfriamento', preco: 380.00 },
    { id: 'P35', descricao: 'Válvula termostática', detalhes: 'Controle térmico', preco: 180.00 },
    { id: 'P36', descricao: 'Bomba d’água', detalhes: 'Circulação', preco: 280.00 },
    { id: 'P37', descricao: 'Mangueira radiador', detalhes: 'Unidade', preco: 120.00 },
    { id: 'P38', descricao: 'Compressor de ar-condicionado', detalhes: 'Climatização', preco: 1200.00 },
    { id: 'P39', descricao: 'Condensador', detalhes: 'Ar-condicionado', preco: 520.00 },
    { id: 'P40', descricao: 'Correia dentada', detalhes: 'Sincronização', preco: 180.00 },
    { id: 'P41', descricao: 'Correia auxiliar', detalhes: 'Acessórios', preco: 120.00 },
    { id: 'P42', descricao: 'Kit embreagem', detalhes: 'Disco, platô e rolamento', preco: 1100.00 },
    { id: 'P43', descricao: 'Bomba de combustível', detalhes: 'Alimentação', preco: 420.00 },
    { id: 'P44', descricao: 'Injetor de combustível', detalhes: 'Unidade', preco: 380.00 },
    { id: 'P45', descricao: 'Coxim do motor', detalhes: 'Unidade', preco: 220.00 },
    { id: 'P46', descricao: 'Junta do cabeçote', detalhes: 'Vedação', preco: 350.00 },
    { id: 'P47', descricao: 'Retentor de óleo', detalhes: 'Vedação', preco: 90.00 },
    { id: 'P48', descricao: 'Palheta limpador', detalhes: 'Par', preco: 80.00 },
    { id: 'P49', descricao: 'Escapamento intermediário', detalhes: 'Sistema de exaustão', preco: 450.00 },
    { id: 'P50', descricao: 'Silencioso traseiro', detalhes: 'Sistema de exaustão', preco: 380.00 }
  ]
};
